export default {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  rules: {
    'custom-property-pattern': null,
    'selector-class-pattern': null,
    'scss/dollar-variable-pattern': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'custom-property-empty-line-before': null,
    'order/properties-order': [
      [
        {
          groupName: 'Позиционирование',
          properties: [
            'content',
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
          ],
        },
        {
          groupName: 'Flexbox',
          properties: [
            'display',
            'flex-direction',
            'flex-wrap',
            'flex-flow',
            'justify-content',
            'align-items',
            'align-content',
            'align-self',
            'flex',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'order',
          ],
        },
        {
          groupName: 'Grid',
          properties: [
            'grid',
            'grid-template',
            'grid-template-columns',
            'grid-template-rows',
            'grid-template-areas',
            'grid-column',
            'grid-row',
            'grid-area',
            'grid-auto-columns',
            'grid-auto-rows',
            'grid-auto-flow',
            'place-items',
            'place-content',
            'place-self',
            'justify-content',
            'align-content',
            'justify-items',
            'align-items',
            'gap',
            'column-gap',
            'row-gap',
          ],
        },
        {
          groupName: 'Блочная модель',
          properties: [
            'float',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-block',
            'margin-inline',
            'padding',
            'padding-block',
            'padding-inline',
          ],
        },
        {
          groupName: 'Типографика',
          properties: [
            'src',
            'font',
            'font-style',
            'font-size',
            'line-height',
            'font-family',
            'text-align',
            'font-weight',
            'letter-spacing',
            'text-transform',
            'text-decoration',
            'white-space',
          ],
        },
        {
          groupName: 'Оформление',
          properties: [
            'color',
            'background-color',
            'background',
            'background-image',
            'background-position',
            'background-size',
            'border',
            'border-radius',
            'opacity',
            'box-shadow',
          ],
        },
        {
          groupName: 'Анимация',
          properties: [
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
          ],
        },
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
  },
}
